spring:
  datasource:
    url: jdbc:h2:mem:api_restful_nuvem
    driverClassName: org.h2.Driver
    username: apirn_gustavo
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  