#Arquivo de Configuração de produção
spring:
  datasource:
    url: jdbc:postgresql://autorack.proxy.rlwy.net:47474/railway 
    username: postgres       
    password: PaxjfMvnstqVZjmUUaFmOGEfGnnkdJmP     
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


